### ISSUE TITLE
在线聊天的功能不正常

### ISSUE THREAD

**Issue by leew995** [guohuadeng/odoo_install_script_cn#4]
今天做了测试，确实不错，不过不知道为什么在线聊天的功能不正常，可以发送附件图片，但是文字发送无显示也无记录，删除数据库重新安装在线聊天模块也不起作用。
求指教！
以下是故障代码：
错误:
Odoo Server Error

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
raise value
File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
result = self._call_function(**self.params)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
result = self.endpoint(*a, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in call
return self.method(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
response = f(*args, **kw)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
return _call_kw_multi(method, model, args, kwargs)
File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_channel.py", line 394, in message_post
message = super(Channel, self.with_context(mail_create_nosubscribe=True)).message_post(message_type=message_type, moderation_status=moderation_status, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/rating/models/mail_thread.py", line 14, in message_post
message = super(MailThread, self).message_post(**kwargs)
File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2065, in message_post
self._message_post_after_hook(new_message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
File "/usr/lib/python3/dist-packages/odoo/addons/mail_bot/models/mail_thread.py", line 12, in _message_post_after_hook
return super(MailThread, self)._message_post_after_hook(message, values, model_description=model_description, mail_auto_delete=mail_auto_delete)
File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 2087, in _message_post_after_hook
mail_auto_delete=mail_auto_delete,
File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_message.py", line 1064, in _notify
rdata = self._notify_compute_recipients(record, msg_vals)
File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_message.py", line 1084, in _notify_compute_recipients
res = self.env['mail.followers']._get_recipient_data(record, subtype_id, pids, cids)
File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_followers.py", line 141, in _get_recipient_data
self.env.cr.execute(query, tuple(params))
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
return f(self, *args, **kwargs)
File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
res = self._obj.execute(query, params)
psycopg2.ProgrammingError: 错误: 字段 "partner.active" 必须出现在 GROUP BY 子句中或者在聚合函数中使用
LINE 12: partner.active as active, partner.partner_share as p...
^

**Comment by leew995** [comment]
另外，我尝试重新安装（之前有快照），发现消息可以发送和接受，但是不是实时的，要刷新网页后才能显示，之前我试过使用官方的Windows一键安装版本，在线即时消息这个功能是实时的，不过不知道为什么网站反应很慢，所以才更换成Ubuntu的版本。
